In [7]:
# Numpy Homework 9               
# Created by Matsenjwa Colani        410921343
# Created on 2019-10-29

# Importing the libraries
import numpy as np

# Define exam scores lists
exam1 = []
exam2 = []

# Read exam scores from user
scores = int(input())
while scores != -1:
    exam1.append(scores)
    scores = int(input())

scores = int(input())
while scores != -1:
    exam2.append(scores)
    scores = int(input())

# Convert lists to numpy arrays
exam1 = np.array(exam1).reshape(3,3)
exam2 = np.array(exam2).reshape(3,3)



In [43]:
results = (exam1 + exam2) * 0.5

# Add 10 points to each student
for i in range(len(results/3)):
    results[i][0] += 10 

# Validate the results
for i in range(results.shape[0]): 
    for j in range(results.shape[1]):
        if results[i][j] > 100:
            results[i][j] = 100
        if results[i][j] < 60:
            results[i][j] = -1

print(exam1)
print()
print(exam2)
print()
print(results)

[[ 65  70  85]
 [ 90 100  70]
 [ 70  50  20]]

[[80 90 60]
 [30 95 60]
 [75 20 80]]

[[82.5 80.  72.5]
 [70.  97.5 65. ]
 [82.5 -1.  -1. ]]
